trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: Kubernetes@1
  displayName: Azure voting app
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: ainhabAKSConnection
    command: apply
    arguments: -f azure-vote-all-in-one-redis.yaml
