trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: Kubernetes@1
  displayName: Azure voting app
  # inputs:
  #   connectionType: Kubernetes Service Connection
  #   kubernetesServiceEndpoint: ainhabAKSConnection
  #   command: apply
  #   arguments: -f - task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'ainhab-serviceaccount-connection'
    kubernetesServiceEndpoint: 'ainhab-serviceaccount-connection'
    namespace: 'default'
    manifests: 'azure-vote-all-in-one-redis.yaml'
